### ISSUE TITLE
unable to merge integration-tag with data-taking CMSSW versions 8_0_14

### ISSUE THREAD

**Issue by bortigno** [cms-l1t-offline/cmssw#395]
bortigno@lxplus049:~/workspace/l1ntuple_8014_v69p0/src$ git cms-merge-topic -u cms-l1t-offline:l1t-integration-v69.0
From .
- [new ref]                    -> merge-attempt
  From https://github.com/cms-l1t-offline/cmssw
- [new ref]         06f43554c64b59e05d26b13995b15e19971c5b7e -> cms-l1t-offline/l1t-integration-v69.0
  Switched to branch 'merge-attempt'
  error: addinfo_cache failed for path 'RecoBTag/CTagging/python/charmTagsComputerCvsL_cfi.py'
  error: addinfo_cache failed for path 'HLTrigger/HLTcore/src/TriggerExpressionL1uGTReader.cc'
  error: addinfo_cache failed for path 'HLTrigger/HLTcore/interface/TriggerExpressionL1uGTReader.h'
  error: addinfo_cache failed for path 'CondTools/BTau/test/test_data2.csv'
  error: addinfo_cache failed for path 'CondTools/BTau/test/test_data.csv'
  error: addinfo_cache failed for path 'CondTools/BTau/test/BTagCalibrationStandalone.h'
  error: addinfo_cache failed for path 'CondTools/BTau/test/BTagCalibrationStandalone.cpp'
  error: addinfo_cache failed for path 'CondTools/BTau/python/generateStandaloneCode.py'
  error: addinfo_cache failed for path 'CondTools/BTau/python/generateFlavCfromFlavB.py'
  error: addinfo_cache failed for path 'CondTools/BTau/python/dataLoader.py'
  error: addinfo_cache failed for path 'CondTools/BTau/python/combineBTagCalibrationData.py'
  error: addinfo_cache failed for path 'CondTools/BTau/python/checkBTagCalibrationConsistency.py'
  error: addinfo_cache failed for path 'CondTools/BTau/python/bTagCalibrationDbCreation.py'
  error: addinfo_cache failed for path 'CondTools/BTau/plugins/BTagCalibrationDbCreator.cc'
  error: addinfo_cache failed for path 'Alignment/MillePedeAlignmentAlgorithm/plugins/RunRangeDependentPedeLabeler.h'
  error: addinfo_cache failed for path 'Alignment/MillePedeAlignmentAlgorithm/plugins/RunRangeDependentPedeLabeler.cc'
  error: addinfo_cache failed for path 'Alignment/MillePedeAlignmentAlgorithm/plugins/PedeLabeler.h'
  error: addinfo_cache failed for path 'Alignment/MillePedeAlignmentAlgorithm/plugins/PedeLabeler.cc'
  error: addinfo_cache failed for path 'Alignment/MillePedeAlignmentAlgorithm/plugins/MomentumDependentPedeLabeler.h'
  error: addinfo_cache failed for path 'Alignment/MillePedeAlignmentAlgorithm/plugins/MomentumDependentPedeLabeler.cc'
  error: addinfo_cache failed for path 'Alignment/MillePedeAlignmentAlgorithm/plugins/MillePedeAlignmentAlgorithm.h'
  error: addinfo_cache failed for path 'Alignment/MillePedeAlignmentAlgorithm/plugins/MillePedeAlignmentAlgorithm.cc'
  Auto-merging L1Trigger/L1TMuonEndCap/src/PatternRecognition.cc
  CONFLICT (content): Merge conflict in L1Trigger/L1TMuonEndCap/src/PatternRecognition.cc
  Automatic merge failed; fix conflicts and then commit the result.
  Unable to merge branch l1t-integration-v69.0 from repository cms-l1t-offline.

**Comment by bortigno** [comment]
Same is true for v77.0 - this is blocking us from producing ntuples from recent runs (post MD1).

From .
- [new ref]                    -> merge-attempt
  From https://github.com/cms-l1t-offline/cmssw
- [new ref]         9d64b80f8188622dc8c11571ca97a287aebeae19 -> cms-l1t-offline/l1t-integration-v77.0
  Switched to branch 'merge-attempt'
  error: addinfo_cache failed for path 'RecoBTag/CTagging/python/charmTagsComputerCvsL_cfi.py'
  error: addinfo_cache failed for path 'HLTrigger/HLTcore/src/TriggerExpressionL1uGTReader.cc'
  error: addinfo_cache failed for path 'HLTrigger/HLTcore/interface/TriggerExpressionL1uGTReader.h'
  error: addinfo_cache failed for path 'CondTools/BTau/test/test_data2.csv'
  error: addinfo_cache failed for path 'CondTools/BTau/test/test_data.csv'
  error: addinfo_cache failed for path 'CondTools/BTau/test/BTagCalibrationStandalone.h'
  error: addinfo_cache failed for path 'CondTools/BTau/test/BTagCalibrationStandalone.cpp'
  error: addinfo_cache failed for path 'CondTools/BTau/python/generateStandaloneCode.py'
  error: addinfo_cache failed for path 'CondTools/BTau/python/generateFlavCfromFlavB.py'
  error: addinfo_cache failed for path 'CondTools/BTau/python/dataLoader.py'
  error: addinfo_cache failed for path 'CondTools/BTau/python/combineBTagCalibrationData.py'
  error: addinfo_cache failed for path 'CondTools/BTau/python/checkBTagCalibrationConsistency.py'
  error: addinfo_cache failed for path 'CondTools/BTau/python/bTagCalibrationDbCreation.py'
  error: addinfo_cache failed for path 'CondTools/BTau/plugins/BTagCalibrationDbCreator.cc'
  error: addinfo_cache failed for path 'Alignment/MillePedeAlignmentAlgorithm/plugins/RunRangeDependentPedeLabeler.h'
  error: addinfo_cache failed for path 'Alignment/MillePedeAlignmentAlgorithm/plugins/RunRangeDependentPedeLabeler.cc'
  error: addinfo_cache failed for path 'Alignment/MillePedeAlignmentAlgorithm/plugins/PedeLabeler.h'
  error: addinfo_cache failed for path 'Alignment/MillePedeAlignmentAlgorithm/plugins/PedeLabeler.cc'
  error: addinfo_cache failed for path 'Alignment/MillePedeAlignmentAlgorithm/plugins/MomentumDependentPedeLabeler.h'
  error: addinfo_cache failed for path 'Alignment/MillePedeAlignmentAlgorithm/plugins/MomentumDependentPedeLabeler.cc'
  error: addinfo_cache failed for path 'Alignment/MillePedeAlignmentAlgorithm/plugins/MillePedeAlignmentAlgorithm.h'
  error: addinfo_cache failed for path 'Alignment/MillePedeAlignmentAlgorithm/plugins/MillePedeAlignmentAlgorithm.cc'
  Auto-merging L1Trigger/L1TMuonEndCap/src/PatternRecognition.cc
  CONFLICT (content): Merge conflict in L1Trigger/L1TMuonEndCap/src/PatternRecognition.cc
  Automatic merge failed; fix conflicts and then commit the result.
  Unable to merge branch l1t-integration-v77.0 from repository cms-l1t-offline.

**Comment by fwyzard** [comment]
hi @bortigno, @rekovic, @mulhearn, 
I think I have resolved the merge conflict between the L1 integration branch and CMSSW_8_0_X.

Can you try if

```
git cms-merge-topic fwyzard:l1t-integration-CMSSW_8_0_16
```

works for you, on top of CMSSW_8_0_16 ?

If you prefer to work in an older release (8.0.13, 8.0.14 or 8.0.15) you can try 

```
git cms-merge-topic fwyzard:l1t-integration-CMSSW_8_0_13
```

instead.

**Comment by fwyzard** [comment]
Just for the record: I have tested that this merges and compiles in CMSSW_8_0_16, but I did not test if any jobs actually work.

**Comment by bortigno** [comment]
Thanks! I am compiling now and test tomorrow. I see that the diff from the l1t-integration-809 is huge: I thought the conflict was only on PatternRecognition.cc? why so much of the L1Trigger package changed?

**Comment by fwyzard** [comment]
Hi Pier,
yes, the only conflict was in PatternRecognition.cc, but in order to prepare a clean starting point for a future merge in CMSSW I made fwyzard:l1t-integration-CMSSW_8_0_16 fully up to date with CMSSW 8.0.16 .
I guess the diff is showing anything that was merged in the release since 8.0.9 : one large PR is #14813 , though there may be others.

**Comment by bortigno** [comment]
Trying to compile in CMSSW_8_0_14 gives me this error: 
/cvmfs/cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_14/lib/slc6_amd64_gcc530/libGeometryCaloGeometry.so: undefined reference to `ESDetId::ESDetId(DetId const&)'
collect2: error: ld returned 1 exit status

> > Deleted: tmp/slc6_amd64_gcc530/src/CondCore/Utilities/bin/conddb_test_gt_load/conddb_test_gt_load
> > config/SCRAM/GMake/Makefile.rules:1917: recipe for target 'tmp/slc6_amd64_gcc530/src/CondCore/Utilities/bin/conddb_test_gt_load/conddb_test_gt_load' failed
> > gmake: **\* [tmp/slc6_amd64_gcc530/src/CondCore/Utilities/bin/conddb_test_gt_load/conddb_test_gt_load] Error 1
> > gmake: **\* [There are compilation/build errors. Please see the detail log above.] Error 2

I am trying 8_0_16 now, though compilation takes forever because of the huge merge, even using --unsafe.

**Comment by bortigno** [comment]
Ok, compilation was huge only in 8_0_14 - 8_0_16 seems to go faster.

**Comment by mulhearn** [comment]
There's a new integration branch based on CMSSW_8_0_17, see issue #403.  This issue is now closed.
